version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: peacewatcher-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    hostname: zookeeperDaemon

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: peacewatcher-kafka
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    hostname: kafkaBroker

  alerts-manager-microservice:
    build: ./Docker/AlertManagerDocker
    container_name: peacewatcher-alerts-manager
    ports:
      - "8501:8501"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC_NAME: "alerts"

  dataviz-microservice:
    build: ./Docker/DataVizDocker
    container_name: peacewatchers-dataviz
    ports:
      - "8502:8502"
